"""empty message

Revision ID: 574d6b6380f7
Revises: bf5280328f5f
Create Date: 2024-03-22 16:59:05.100572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574d6b6380f7'
down_revision = 'bf5280328f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_num', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('order_num')

    # ### end Alembic commands ###
